#!/usr/bin/env python
from distutils.core import setup

setup(
    name='game-of-life',
    version='1.0',
    author='RAKAI Mohamed',
    license='MIT',
    long_description=open('README.md').read(),
)
